"""two_unique_fields

Revision ID: affa94d73e5f
Revises: 2eb900903ebf
Create Date: 2026-04-11 17:25:37.179270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affa94d73e5f'
down_revision: Union[str, Sequence[str], None] = '2eb900903ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_oauth_provider', ['provider', 'provider_user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('unique_oauth_provider', type_='unique')

    # ### end Alembic commands ###
